version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "6500:6500"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"